[package]
name = "clipboard"
version = "0.1.0"
authors = ["Maximilian Burszley <mburszley@gmail.com>"]
edition = "2018"

[build-dependencies]
windows = "0.8.0"

[dependencies]
thiserror = "1.0.24"
windows = "0.8.0"
