[package]
name = "mono"
version = "0.1.0"
authors = ["Maximilian Burszley <mburszley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = { path = "../clipboard" }
once_cell = "1.7.2"
